server:
  port: 8081
  servlet:
    context-path: /app
    session:
      cookie:
        http-only: true
        secure: true
spring:
  jackson:
    serialization:
      indent-output: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
  jpa:
    database: postgresql
    show-sql: true
    hibernate.ddl-auto: create
    properties.hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


