//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.05 at 01:12:12 PM GMT+03:00 
//


package com.geekbrains.soap.product;

import jakarta.xml.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="productSoap" type="{http://geekbrains.com/product}productSoap" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "productSoap"
})
@XmlRootElement(name = "getProductsByFilterResponse")
public class GetProductsByFilterResponse {

    @XmlElement(required = true)
    protected List<ProductSoap> productSoap;

    /**
     * Gets the value of the productSoap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the productSoap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductSoap().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductSoap }
     * 
     * 
     */
    public List<ProductSoap> getProductSoap() {
        if (productSoap == null) {
            productSoap = new ArrayList<ProductSoap>();
        }
        return this.productSoap;
    }

}
