//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.05 at 01:12:12 PM GMT+03:00 
//


package com.geekbrains.soap.product;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.geekbrains.product package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.geekbrains.product
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetProductsByFilterRequest }
     * 
     */
    public GetProductsByFilterRequest createGetProductsByFilterRequest() {
        return new GetProductsByFilterRequest();
    }

    /**
     * Create an instance of {@link GetProductsByFilterResponse }
     * 
     */
    public GetProductsByFilterResponse createGetProductsByFilterResponse() {
        return new GetProductsByFilterResponse();
    }

    /**
     * Create an instance of {@link ProductSoap }
     * 
     */
    public ProductSoap createProductSoap() {
        return new ProductSoap();
    }

}
